#pragma once

#define APP_TITLE "sustmail"
#define APP_VERSION "1.0"

#define DOMAIN_NAME g_szDomain
#define DOMAIN_ROOT_PATH g_szDomainPath
#define USER_MAIL_DIRECTORY_NAME "mbox"

#define MSG_SEARCH_WILDCARD "*.eml"


//POP3 Defines

#define POP3_PORT 110

#define POP3_STATE_AUTHORIZATION 1
#define POP3_STATE_TRANSACTION 2
#define POP3_STATE_UPDATE 4

#define POP3_DEFAULT_NEGATIVE_RESPONSE 0
#define POP3_DEFAULT_AFFERMATIVE_RESPONSE 1
#define POP3_WELCOME_RESPONSE 2

#define POP3_STAT_RESPONSE 16

#define POP3_MSG_STATUS_UNDEFINED 0
#define POP3_MSG_STATUS_NEW 1
#define POP3_MSG_STATUS_READ 2
#define POP3_MSG_STATUS_REPLIED 4
#define POP3_MSG_STATUS_DELETED 8
#define POP3_MSG_STATUS_CUSTOM 16


//SMTP Defines

#define SMTP_PORT 25

#define SMTP_DATA_TERMINATOR "\r\n.\r\n"

#define SMTP_STATUS_INIT 1
#define SMTP_STATUS_HELO 2
#define SMTP_STATUS_DATA 16
#define SMTP_STATUS_DATA_END 32

#define SMTP_CMD_HELO "HELO"
#define SMTP_CMD_EHLO "EHLO"
#define SMTP_CMD_MAIL "MAIL"
#define SMTP_CMD_RCPT "RCPT"
#define SMTP_CMD_DATA "DATA"
#define SMTP_CMD_RSET "RSET"
#define SMTP_CMD_NOOP "NOOP"
#define SMTP_CMD_QUIT "QUIT"

#define SMTP_CMD_VRFY "VRFY"
#define SMTP_CMD_EXPN "EXPN"


//SMTP (RFC 821) DEFINED VALUES
#define MAX_USER_LENGTH 64 
#define MAX_DOMAIN_LENGTH 64
#define MAX_ADDRESS_LENGTH 256
#define MAX_CMD_LENGTH 512
#define MAX_RCPT_ALLOWED 100